# Use official Node.js 12 image
FROM node:12

# Set working directory
WORKDIR /workspace


# Set user permissions
RUN chown -R node:node /workspace
USER node

# Expose React's default port
EXPOSE 3000
